import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Next.js Tutorial - MTM",
    template: "%s | MTM",
    absolute: "",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="bg-blue-400 py-4">
          <p>Header</p>
        </header>
        {children}
        <footer className="bg-blue-400 py-4-">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
